In [12]:
!pip install loguru io3d pydicom sed3
!pip install git+https://github.com/mjirik/imma.git
!pip install ruamel_yaml

  Cloning https://github.com/mjirik/imma.git to /tmp/pip-req-build-2_9t7_ut
  Running command git clone --filter=blob:none --quiet https://github.com/mjirik/imma.git /tmp/pip-req-build-2_9t7_ut
  Resolved https://github.com/mjirik/imma.git to commit d0d6adad07fb1a298fbe1d4f525b690d9aedd1d1
  Preparing metadata (setup.py) ... done


In [13]:
from loguru import logger
import io3d
import io3d.datasets
import sed3
import numpy as np
import matplotlib.pyplot as plt
logger.enable("io3d")
logger.disable("io3d")
import matplotlib.pyplot as plt
import h5py
import json
from pathlib import Path

import sys
import os
print(sys.version_info)
print(sys.executable)
print(os.getcwd())

sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
/usr/bin/python3
/content


In [14]:
!wget https://cloud.ircad.fr/index.php/s/JN3z7EynBiwYyjy/download -O ./dataset.zip

--2024-04-12 08:58:30--  https://cloud.ircad.fr/index.php/s/JN3z7EynBiwYyjy/download
Resolving cloud.ircad.fr (cloud.ircad.fr)... 130.79.192.40
Connecting to cloud.ircad.fr (cloud.ircad.fr)|130.79.192.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘./dataset.zip’

./dataset.zip           [     <=>            ] 782.26M  14.9MB/s    in 58s     

2024-04-12 08:59:30 (13.5 MB/s) - ‘./dataset.zip’ saved [820260524]



In [15]:
%cd /root/data/medical/orig
!pwd
!unzip /content/dataset.zip

/root/data/medical/orig
/root/data/medical/orig
Archive:  /content/dataset.zip
   creating: 3Dircadb1/
   creating: 3Dircadb1/3Dircadb1.1/
 extracting: 3Dircadb1/3Dircadb1.1/LABELLED_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.1/LICENSE.txt  
 extracting: 3Dircadb1/3Dircadb1.1/MASKS_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.1/MESHES_VTK.zip  
 extracting: 3Dircadb1/3Dircadb1.1/PATIENT_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.1/liver_01.jpg  
   creating: 3Dircadb1/3Dircadb1.10/
 extracting: 3Dircadb1/3Dircadb1.10/LABELLED_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.10/LICENSE.txt  
 extracting: 3Dircadb1/3Dircadb1.10/MASKS_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.10/MESHES_VTK.zip  
 extracting: 3Dircadb1/3Dircadb1.10/PATIENT_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.10/liver_10.jpg  
   creating: 3Dircadb1/3Dircadb1.11/
 extracting: 3Dircadb1/3Dircadb1.11/LABELLED_DICOM.zip  
 extracting: 3Dircadb1/3Dircadb1.11/LICENSE.txt  
 extracting: 3Dircadb1/3Dircadb1.11/MASKS_DI

In [16]:
io3d.datasets.get_dataset_path("sliver07", "data3d", 1)

PosixPath('/root/data/medical/orig/sliver07/training/liver-orig001.mhd')

In [17]:
io3d.datasets.get_dataset_path("3Dircadb1", "data3d", 1)

PosixPath('/root/data/medical/orig/3Dircadb1.1/PATIENT_DICOM')

In [19]:
%cd /root/data/medical/orig/3Dircadb1.1/

/root/data/medical/orig/3Dircadb1.1


In [20]:
!unzip PATIENT_DICOM.zip

Archive:  PATIENT_DICOM.zip
   creating: PATIENT_DICOM/
  inflating: PATIENT_DICOM/image_0   
  inflating: PATIENT_DICOM/image_1   
  inflating: PATIENT_DICOM/image_10  
  inflating: PATIENT_DICOM/image_100  
  inflating: PATIENT_DICOM/image_101  
  inflating: PATIENT_DICOM/image_102  
  inflating: PATIENT_DICOM/image_103  
  inflating: PATIENT_DICOM/image_104  
  inflating: PATIENT_DICOM/image_105  
  inflating: PATIENT_DICOM/image_106  
  inflating: PATIENT_DICOM/image_107  
  inflating: PATIENT_DICOM/image_108  
  inflating: PATIENT_DICOM/image_109  
  inflating: PATIENT_DICOM/image_11  
  inflating: PATIENT_DICOM/image_110  
  inflating: PATIENT_DICOM/image_111  
  inflating: PATIENT_DICOM/image_112  
  inflating: PATIENT_DICOM/image_113  
  inflating: PATIENT_DICOM/image_114  
  inflating: PATIENT_DICOM/image_115  
  inflating: PATIENT_DICOM/image_116  
  inflating: PATIENT_DICOM/image_117  
  inflating: PATIENT_DICOM/image_118  
  inflating: PATIENT_DICOM/image_119  
  inflating:

## Check few slides

In [32]:
np.__version__

'1.25.2'

In [21]:
experiment_label = "liver_slides"

In [36]:
datap1 = io3d.datasets.read_dataset("3Dircadb1", "data3d", 1)
# datap1 = io3d.datasets.read_dataset("sliver07", "data3d", 1)
# print(datap1)
data3d = datap1["data3d"]
print(data3d)
# sed3.show_slices(data3d, shape=[2,3])
plt.figure()

[[[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 ...

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -10

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [29]:
np.__version__

'1.25.2'